grid_map_topic: /traversability_gridmap

grid_map_visualizations:

  - name: elevation_points
    type: point_cloud
    params:
     layer: elevation
    
  - name: elevation_grid
    type: occupancy_grid
    params:
     layer: elevation
     data_min: 0.08
     data_max: -0.16

  - name: elevation_cells
    type: grid_cells
    params:
     layer: elevation
     lower_threshold: -0.6
     upper_threshold: 0.05

  - name: traversability_cells
    type: grid_cells
    params:
     layer: traversability
     lower_threshold: 1
     upper_threshold: 255
     
  - name: surface_normals
    type: vectors
    params:
     layer_prefix: normal_
     position_layer: elevation
     scale: 0.06
     line_width: 0.005
     color: 15600153 # red
 
